[package]
name = "RobloxMemAPI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "RobloxMemAPI"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
winapi = "0.3.9"
windows = "0.61.3"
